version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_IP=${HOST_IP:-localhost}
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - HOST_IP=${HOST_IP:-localhost}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    restart: always