version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # Maps local port 80 to container $PORT (default 80)
    environment:
      - PORT=80 # Simulating Render's $PORT
      - JWT_SECRET=${JWT_SECRET}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    restart: always