version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://${HOST_IP}:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/blogDB
      - PORT=3000
      - HOST_IP=${HOST_IP}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - CLOUD_NAME=${CLOUD_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: